import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

import AuthProvider from "./providers/SessionProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

declare global {
  interface BigInt {
    toJSON(): string;
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString();
};
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar title="Next Learning App" />


         <div className="flex grow">
        
        <aside className="w-64 bg-black text-white p-4">
          Dashboard Sidebar
        </aside>

        <main className="flex grow p-10">
          <AuthProvider>
          {children}
        </AuthProvider>
        </main>
      </div>

        <footer className="w-full bg-gray-800 text-white p-4 text-center">
        © 2026 Your Brand
      </footer>
      </body>
    </html>
  );
}
